# .air.toml
[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
delay = 1000ms
kill_delay = 0ms
stop_on_error = false

[log]
level = "debug"

[color]
main = "magenta"

[screen]
clear_on_rebuild = true
keep_scroll = true