CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    user_group_id INT NOT NULL REFERENCES user_groups(id) ON DELETE SET NULL ON UPDATE CASCADE,
    role VARCHAR(100) NOT NULL CHECK (role IN ('user', 'admin')),
    name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    nrp VARCHAR(100) NOT NULL,
    last_login TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by INT NOT NULL REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by INT NOT NULL REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
