CREATE TABLE IF NOT EXISTS menus (
  id SERIAL PRIMARY KEY,
  paret_id INT REFERENCES menus(id) ON DELETE SET NULL ON UPDATE CASCADE,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
